# Generated by Django 3.0.8 on 2020-07-22 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200721_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='/default.jpg', upload_to='profilePictures/'),
        ),
    ]
