# Generated by Django 3.0.8 on 2020-07-29 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200728_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_choreos',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_covers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='suggested_choreos',
        ),
        migrations.RemoveField(
            model_name='post',
            name='suggested_covers',
        ),
        migrations.AddField(
            model_name='video_tile',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='accounts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_tile',
            name='tile_type',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
