# Generated by Django 3.0.8 on 2020-07-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200729_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_tile',
            name='is_youtube',
            field=models.BooleanField(default=False),
        ),
    ]
