# Generated by Django 3.1.2 on 2020-12-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_feed_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video_Tile',
            new_name='Tile',
        ),
    ]
