# Generated by Django 3.0.8 on 2021-01-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_item',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Follower'),
        ),
    ]
