# Generated by Django 3.0.8 on 2021-01-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210113_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notification_token',
            field=models.CharField(error_messages={'unique': 'Token is already assigned.'}, max_length=50, null=True, unique=True),
        ),
    ]
