# Generated by Django 3.0.8 on 2021-02-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_account_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='soundcloud_account',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='spotify_account',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='youtube_account',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
