# Generated by Django 3.0.8 on 2021-02-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210207_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='soundcloud_search_query',
            field=models.CharField(max_length=200),
        ),
    ]
