# Generated by Django 3.1.4 on 2021-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210207_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='song_genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='song_label_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
