# Generated by Django 3.1.4 on 2021-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210222_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_genre',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='song_label_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
