# Generated by Django 3.1.4 on 2021-02-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210222_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_genre',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='song_label_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
