# Generated by Django 3.1.4 on 2021-02-23 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210223_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.follower')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
