# Generated by Django 3.0.8 on 2021-02-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_explore_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore_item',
            name='follow_relation',
        ),
    ]
