# Generated by Django 3.1.4 on 2021-03-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_explore_item_follow_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='video_id',
            field=models.CharField(default='', max_length=11),
        ),
    ]
