# Generated by Django 3.1.4 on 2021-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_tile_video_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(default='', max_length=11)),
                ('audio_url', models.CharField(default='', max_length=2000)),
                ('song_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('thumbnail', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
