# Generated by Django 3.1.4 on 2021-03-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='soundcloud_art',
            new_name='album_cover',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='soundcloud_audio',
            new_name='audio_url',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='soundcloud_search_query',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='song_genre',
            new_name='song_tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='song_label_name',
        ),
    ]
