# Generated by Django 3.1.4 on 2021-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210316_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artist_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
