# Generated by Django 3.1.4 on 2021-03-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_post_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
    ]
