# Generated by Django 3.1.4 on 2021-04-03 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210403_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagged',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tagged', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagger', to=settings.AUTH_USER_MODEL),
        ),
    ]
