# Generated by Django 3.1.4 on 2021-04-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210403_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='link',
            new_name='youtube_link',
        ),
        migrations.RenameField(
            model_name='tile',
            old_name='video_created',
            new_name='youtube_video_created',
        ),
        migrations.RenameField(
            model_name='tile',
            old_name='video_id',
            new_name='youtube_video_url',
        ),
        migrations.AddField(
            model_name='tile',
            name='custom_video_url',
            field=models.FileField(blank=True, null=True, upload_to='videoUploads/'),
        ),
    ]
