# Generated by Django 3.1.4 on 2021-04-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210406_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
