# Generated by Django 3.1.4 on 2021-04-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20210413_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
