# Generated by Django 3.0.8 on 2021-06-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210413_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_item',
            name='follow_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Follower'),
        ),
    ]
