# Generated by Django 3.0.8 on 2021-12-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210626_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='youtube_video_url',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
